export default {
  data: [
    {
      _id: { $oid: '5ea097ebeca3ca2dd7e7c77d' },
      name: 'Slender',
      pic: 'slender-screen.png',
      picBlur: 'slender-screen-blur.jpg',
      icon: ['fas', 'gamepad'],
      text: 'Loerm ipsum dalor',
      url: 'https://elkinuk.github.io/Slender/',
    },
    {
      _id: { $oid: '5ea097ebeca3ca2dd7e7c77e' },
      name: 'News app',
      pic: 'news-app-screen.png',
      picBlur: 'news-app-screen-blur.jpg',
      url: 'https://elkinny.github.io/NewsAPI/news-app/index.html',
      icon: ['fab', 'js-square'],
      iconColour: '#ffce54',
    },
    {
      _id: { $oid: '5ea097ebeca3ca2dd7e7c77f' },
      name: 'News app',
      pic: 'news-app-ng-screen.png',
      picBlur: 'news-app-ng-screen-blur.jpg',
      text: 'Loerm ipsum dalor',
      url: 'https://elkinny.github.io/NewsAPI/news-ng',
      icon: ['fab', 'angular'],
      iconColour: '#ed5565',
    },
    {
      _id: { $oid: '5ea097ebeca3ca2dd7e7c780' },
      name: 'Movie app',
      icon: ['fab', 'react'],
      iconColour: '#5d9cec',
      url: '#',
    },
    {
      _id: { $oid: '5ea097ebeca3ca2dd7e7c781' },
      name: 'Movie app',
      pic: 'movie-app-vue-screen.png',
      picBlur: 'movie-app-vue-screen-blur.jpg',
      text: 'Loerm ipsum dalor',
      url: 'https://elkinny.github.io/Simple-Vue-App/',
      icon: ['fab', 'vuejs'],
      iconColour: '#2ecc71',
    },
  ],
};
